# Use an official Node.js runtime as a parent image
FROM node:22

ENV MEETINGS_APP_ENV="uat"

# Set the working directory in the container
WORKDIR /video_app

# Copy the rest of the application code
COPY . .

# Move into MaxLabProject directory
WORKDIR /video_app/videoserver

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["npm", "start"]