services:
    meetings_app:
        build:
            context: .
            dockerfile: Dockerfile.meetings_app
        container_name: meetings_container
        volumes:
            - static_volume:/app/MaxLabProject/staticfiles
        restart: always
        ports:
            - "8000:8000"

    frontend-proxy:
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - static_volume:/app/MaxLabProject/staticfiles:ro
        depends_on:
            - meetings_app

volumes:
    static_volume:
