services:
    meetings_app:
        build:
            context: .
            dockerfile: Dockerfile.meetings_app
        env_file:
            - .env
        container_name: meetings_container
        volumes:
            - static_volume_meetings_app:/app/MaxLabProject/staticfiles
        restart: always

    videoserver:
        build:
            context: .
            dockerfile: Dockerfile.videoserver
        env_file:
            - .env
        container_name: videoserver
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - static_volume_videoserver:/app/videoserver/public/
            - ${LOCAL_RECORDING_LOCATION}:/app/LocalRecordings
        restart: always

    frontend-proxy:
        build:
            context: .
            dockerfile: Dockerfile.nginx
            args:
                CERT_DOMAIN: ${CERT_DOMAIN}
        env_file:
            - .env
        ports:
            - 80:80
            - 443:443
        container_name: frontend_proxy
        volumes:
            - static_volume_meetings_app:/app/MaxLabProject/staticfiles:ro
            - static_volume_videoserver:/app/videoserver/public/:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
        entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
        depends_on:
            - meetings_app
            - videoserver

volumes:
    static_volume_meetings_app:
    static_volume_videoserver:
