# Generated by Django 2.2.5 on 2022-04-03 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('number_of_participants', models.IntegerField(default=2)),
                ('duration', models.IntegerField(default=3)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('is_audio_enabled', models.BooleanField(default=True)),
                ('is_video_enabled', models.BooleanField(default=True)),
                ('is_recording_audio_enabled', models.BooleanField(default=True)),
                ('is_recording_video_enabled', models.BooleanField(default=True)),
                ('is_transcription_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(default='NOT STARTED', max_length=100)),
                ('meeting_start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Room_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('meeting_start_time', models.DateTimeField()),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='video_app.Room')),
            ],
        ),
    ]
