# Generated by Django 3.2.6 on 2024-06-11 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('number_of_participants', models.IntegerField(default=2)),
                ('duration', models.IntegerField(default=30)),
                ('resolution', models.CharField(default='640x480', max_length=10)),
                ('frame_rate', models.IntegerField(default=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('is_audio_enabled', models.BooleanField(default=True)),
                ('is_video_enabled', models.BooleanField(default=True)),
                ('is_recording_audio_enabled', models.BooleanField(default=True)),
                ('is_recording_video_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='NOT STARTED', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room_History',
            fields=[
                ('room_hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='Exp', max_length=250)),
                ('number_of_participants', models.IntegerField(default=2)),
                ('duration', models.IntegerField(default=30)),
                ('resolution', models.CharField(default='640x480', max_length=10)),
                ('frame_rate', models.IntegerField(default=30)),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('meeting_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_audio_enabled', models.BooleanField(default=True)),
                ('is_video_enabled', models.BooleanField(default=True)),
                ('is_recording_audio_enabled', models.BooleanField(default=True)),
                ('is_recording_video_enabled', models.BooleanField(default=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='video_app.room')),
            ],
        ),
    ]
