# Generated by Django 2.2.5 on 2022-04-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20220403_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_history',
            name='session_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
