# Generated by Django 2.2.5 on 2022-04-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_auto_20220409_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='frame_rate',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='room',
            name='resolution',
            field=models.CharField(default='640x480', max_length=10),
        ),
        migrations.AddField(
            model_name='room_history',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
