# Generated by Django 2.2.5 on 2022-05-23 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_auto_20220415_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_history',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='room_history',
            name='frame_rate',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='room_history',
            name='is_audio_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room_history',
            name='is_recording_audio_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room_history',
            name='is_recording_video_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room_history',
            name='is_transcription_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_history',
            name='is_video_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room_history',
            name='number_of_participants',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room_history',
            name='resolution',
            field=models.CharField(default='640x480', max_length=10),
        ),
        migrations.AddField(
            model_name='room_history',
            name='room_name',
            field=models.CharField(default='Exp', max_length=250),
        ),
        migrations.AlterField(
            model_name='room_history',
            name='meeting_start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
