# Generated by Django 2.2.5 on 2022-12-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_auto_20220523_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_transcription_enabled',
        ),
        migrations.RemoveField(
            model_name='room_history',
            name='is_transcription_enabled',
        ),
    ]
